;*********************************************************
; Konstanty dlya uchebnogo primera laboratornoy raboty N 1  *
; po MOP. 10.09.02: Negoda V.N.                           *
;*********************************************************

CHESC	= 1Bh	
CHCR	= 13
CHSEP	= '='
CHCOMMA = '`'
CHLF	= 10
DOSFU	= 21h
FUPUTC 	= 2
FUGETCH = 8
FUGETS  = 0Ah
FUEXIT  = 4Ch
PAUSE_L	= 0000	; Mladshee slovo startovogo znacheniya pauzy
PAUSE_H	= 0	; Starshee slovo
LENNUM	= 18	; Chislo simvolov v stroke desyatichnogo chisla  
LENPACK = 9	; Upakovonnoe v dva raza koroche
